---

- set_fact:
    chatbot_service: |
      chatbot:
        restart: always
        build:
            context: ./dockerfile/chatbot/
            dockerfile: {{ dockerfile }}
        volumes:
            - chatbot_src:/usr/src/errbot/
            - chatbot_data:/usr/src/errbot/data
            - ./{{ config_dir_basename }}/chatbot:/etc/errbot/:ro
        env_file:
            - ./{{ env_dir_basename }}/{{ chatbot_env_file_basename }}
        command: errbot

    chatbot_volumes: |
      chatbot_src: ~
      chatbot_data: ~

- name: chatbot | Add services to docker-compose.yml
  blockinfile:
    dest: "{{ docker_compose_filepath }}"
    insertafter: "^services:$"
    marker: "  # {mark} CHATBOT SERVICES - ANSIBLE MANAGED BLOCK #"
    block: "{{ chatbot_service | indent(2, true) }}"

- name: chatbot | Add volumes to docker-compose.yml
  blockinfile:
    dest: "{{ docker_compose_filepath }}"
    insertafter: "^volumes:$"
    marker: "  # {mark} CHATBOT VOLUMES - ANSIBLE MANAGED BLOCK #"
    block: "{{ chatbot_volumes | indent(2, true) }}"
