---

# Prepare directories
- name: chatbot | Create directories
  file:
    path: '{{ item }}'
    state: directory
    owner: '{{ user }}'
    group: '{{ group }}'
  with_items:
    - '{{ chatbot_dockerfiles_dir }}'
    - '{{ chatbot_config_dir }}'
    - '{{ chatbot_config_plugins_dir }}'

- name: chatbot | Create plugin config folders
  file:
    path: '{{ item }}'
    state: directory
    owner: '{{ user }}'
    group: '{{ group }}'
  with_items:
    - '{{ chatbot_config_plugins_dir }}/err-rss'
    - '{{ chatbot_config_plugins_dir }}/err-sponsors'
    #- '{{ chatbot_config_plugins_dir }}/err-gdrive'

- name: chatbot | Copy tokens.yml file
  copy:
    src: config/tokens.yml
    dest: '{{ chatbot_config_dir }}'
  notify: chatbot restart

- name: chatbot | Copy env file
  copy:
    src: env
    dest: '{{ dockers_env_dir }}/{{ chatbot_env_file_basename }}'
  notify: chatbot restart

- name: chatbot | Copy Dockerfile file
  copy:
    src: '{{ dockerfile }}'
    dest: '{{ chatbot_dockerfiles_dir }}/{{ dockerfile }}'
  notify: chatbot restart

- import_tasks: plugins.yml
  tags: [chatbot_docker, chatbot_plugins]
  notify: chatbot restart

- import_tasks: docker_compose.yml
  tags: chatbot_docker
  notify: chatbot restart

- name: chatbot | make sure all handlers run
  meta: flush_handlers
