---

- name: chatbot | Copy err-rss plugin config files
  copy:
    src: 'config/plugins/err-rss/{{ item.src }}'
    dest: '{{ chatbot_config_plugins_dir }}/err-rss/{{ item.dest }}'
  with_items:
    - { src: 'err-rss-vault.ini', dest: 'err-rss.ini' }
  notify: chatbot restart

- name: chatbot | Copy err-sponsors plugin config files
  copy:
    src: 'config/plugins/err-sponsors/{{ item.src }}'
    dest: '{{ chatbot_config_plugins_dir }}/err-sponsors/{{ item.dest }}'
  with_items:
    - { src: 'google_api_key.json', dest: 'google_api_key.json' }
    - { src: 'sponsor_agreement_template_eps-vault.tex', dest: 'sponsor_agreement_template_eps-vault.tex' }
  notify: chatbot restart

# - name: chatbot | Copy err-gdrive plugin config files
#   copy:
#     src: 'config/plugins/err-gdrive/{{ item.src }}'
#     dest: '{{ chatbot_config_plugins_dir }}/err-gdrive/{{ item.dest }}'
#   with_items:
#     - { src: 'client_secrets.json', dest: 'client_secrets.json' }
#     - { src: 'pydrive_settings.yml', dest: 'pydrive_settings.yml' }
