---

- name: Install docker
  shell: curl -sSL https://get.docker.com | sh

- name: Install docker-compose and docker-py
  pip:
    name: '{{ item }}'
    state: forcereinstall
  with_items:
    - docker-py
    - docker-compose

- name: Add docker group
  group:
    name: docker
    state: present

- name: Add user to docker group
  user:
    name: "{{ user }}"
    groups: docker
    append: yes
