---

- name: chatbot | docker-compose.yml template file
  template:
    src: docker-compose.yml.j2
    dest: "{{ dockers_dir }}/docker-compose.yml"
    mode: 0640

- name: chatbot | docker-compose service is absent
  docker_service:
    project_src: "{{ dockers_dir }}"
    project_name: chatbot
    state: absent

- name: chatbot | Launch docker-compose service
  docker_service:
    project_src: "{{ dockers_dir }}"
    project_name: chatbot
  register: output

- name: chatbot | Debug docker-compose service
  debug:
    var: output

- name: chatbot | Check docker-compose service is running
  assert:
    that:
      - "errbot.chatbot.state.running"
